version: 3

includes:
    docker:
        taskfile: git@github.com:skidoosh/taskfiles.git//docker.yaml?ref=main
    python:
        taskfile: git@github.com:skidoosh/taskfiles.git//python.yaml?ref=main
